Add khanh's lesson 4
trainingdeveloperpro/android-k001 pull request #12
Opened 2019-07-29 09:55 UTC by JKhanh

2019-07-29 10:34 UTC, truongnguyenptit commented on app/src/main/java/com/traningdeveloperpro/androidk001/lesson4/nguyenquockhanh/linearlogin/MainActivity.kt
> +        val edit_text_email = findViewById<EditText>(R.id.edit_text_email)
trong kotlin thì code theo lưng lạc đà e nhé, camelCase ấy

2019-07-29 10:34 UTC, truongnguyenptit commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:layout_width="@dimen/width_bigEditText"
cái này đặt tên vẫn bị này e width_bigEditText

2019-07-29 10:35 UTC, truongnguyenptit commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:id="@+id/edit_text_register_pass"
edit_text_register_pass
ghi rõ là edit_text_register_password

2019-07-29 10:35 UTC, truongnguyenptit requested changes
@JKhanh

2019-07-30 01:49 UTC, JKhanh commented
@truongnguyenptit e đã sửa hết lỗi trên r anh ạ

2019-07-31 06:30 UTC, closed without merging