Add khanh's lesson 5
trainingdeveloperpro/android-k001 pull request #14
Opened 2019-07-31 16:15 UTC by JKhanh

please check my code

2019-08-01 03:56 UTC, truongnguyenptit requested changes

2019-08-01 03:56 UTC, truongnguyenptit commented on app/src/main/res/drawable/border.xml
> +       android:shape="rectangle" android:padding="10dp">
ở trong này cũng không hard code nhé

2019-08-01 03:56 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/StudentViewHolder.kt
> +    private var mName: TextView? = null
mName là java convention, e xem lại kotlin convention nhé

2019-08-01 03:56 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/MyAdapter.kt
> +class MyAdapter(private val items: ArrayList<Student>) : RecyclerView.Adapter<StudentViewHolder>() {
class đặt clear hơn nhé: VD: StudentAdapter

2019-08-01 03:56 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
Không dùng fragment à em?

2019-08-01 08:57 UTC, JKhanh commented
Code đã đk sửa r anh ạ

2019-08-02 01:59 UTC, truongnguyenptit commented
Conflict e oi

2019-08-02 08:20 UTC, JKhanh commented
e fix xong r anh ơi

2019-08-03 01:51 UTC, merged