Add khanh's lesson 6
trainingdeveloperpro/android-k001 pull request #22
Opened 2019-08-03 09:59 UTC by JKhanh

2019-08-05 13:35 UTC, JKhanh commented
conflict fixed @truongnguyenptit

2019-08-05 13:50 UTC, linhvnguyen9 reviewed
Ô check code và refactor lại cho clean nhé

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/StudentViewHolder.kt
> +    private var userTelephone: TextView? = null
Đoạn này có thể dùng lateinit để đỡ phải gán giá trị null
```suggestion
    private lateinit var userTelephone: TextView
```

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/Student.kt
> +data class Student(val name : String,val  age : String, val telephone : String)
đoạn này nên Ctrl +Alt +Shift + L format lại cho chuẩn 1 code style

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/AddFragment.kt
> +const val NAME : String = "name"
Nên đổi tên biến lại cho chuẩn coding convention
```suggestion
const val EXTRA_STUDENT_NAME : String = "name"
```

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/StudentAdapter.kt
> +        val student: Student = items[position]
Đoạn này Kotlin cho phép không cần khai báo kiểu
```suggestion
        val student = items[position]
```

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/StudentAdapter.kt
> +        holder.buttonDelete?.setOnClickListener {
Nên cho hết nội dung của setOnClickListener vào 1 hàm private để gọn hơn. Như vậy setOnClickListener chỉ chứa 1 lời gọi hàm

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/StudentDiffUtil.kt
> +    override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean {
areContentsTheSame nên check đủ tất cả thuộc tính của Student, đề phòng trường hợp 2 người khác nhau nhưng trùng tên

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/StudentListFragment.kt
> +        studentList.add(Student("Anh", "20", "53165435"))
Nên gom hết chỗ tạo Student vào 1 hàm cho gọn

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/res/layout/activity_add_new.xml
> +            tools:layout_editor_absoluteY="16dp" tools:layout_editor_absoluteX="16dp" android:id="@+id/fragment2"/>
Nên fix hardcode ở chỗ này

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/res/values/dimens.xml
> +    <dimen name="small_space">30dp</dimen>
Chỗ này nên đặt tên rõ hơn chút. Tham khảo coding convention nhé

2019-08-05 13:50 UTC, vanlinh999 commented on lesson6Khanh/src/main/res/values/strings.xml
> +    <string name="age">Student Age</string>
Chỗ này cũng nên đặt tên lại cho rõ, tham khảo coding convention

2019-08-06 02:03 UTC, truongnguyenptit requested changes

2019-08-06 02:03 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/AddFragment.kt
> +const val NAME : String = "name"
Xem lại convention của Riot e nhé, link a gửi trước đó ấy.

2019-08-06 02:03 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson5/nguyenquockhanh/studentlist/AddNew.kt
> +        val button = add_button as Button
Chưa được clean lắm nhỉ

2019-08-12 01:41 UTC, merged