Add khanh's leson 3
trainingdeveloperpro/android-k001 pull request #8
Opened 2019-07-26 09:55 UTC by JKhanh

I have fixed naming to right convention, reduced hardcode and changed debug log to new way

2019-07-26 11:12 UTC, truongnguyenptit commented
Conflict kìa e ơi

2019-07-26 11:26 UTC, JKhanh commented
confict fixed

2019-07-28 06:40 UTC, truongnguyenptit commented on app/src/main/res/values/dimens.xml
> +    <dimen name="textBigSize">40sp</dimen>
Naming chỗ này e viết thuơgnf và có dấu gạch dưới nhé
theo <WHAT>_<WHERE>_<DESCRIPTION>_<SIZE>

2019-07-28 06:41 UTC, truongnguyenptit commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:id="@+id/registerPass"
Đưng viết tắt e nhé ghi rõ nó ra. VD: edit_text_register_password
<WHAT>_<WHERE>_<DESCRIPTION>

2019-07-28 06:42 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson3/nguyenquockhanh/signUp.kt
> +val TAG : String = "MyActivity"
DĐổi lại thành private const val TAG = SignUp::java.class.simpleName()

2019-07-28 06:42 UTC, truongnguyenptit commented on app/src/main/java/com/trainingdeveloperpro/androidk001/lesson3/nguyenquockhanh/signUp.kt
> +class signUp : AppCompatActivity() {
class là danh từ nên viết Hoa hết nhé

2019-07-28 06:43 UTC, truongnguyenptit requested changes
Sửa lại 1 chút nữa là được e nhé

2019-07-28 13:35 UTC, JKhanh commented
E sửa lại r a check lại cho e với

2019-07-30 01:39 UTC, JKhanh commented
@truongnguyenptit check lai cho e voi a oi

2019-07-31 01:59 UTC, truongnguyenptit approved these changes

2019-07-31 01:59 UTC, merged